language: python
cache: pip
sudo: true
addons:
  apt:
    update: true
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy3.5
env:
  global: PYTHONHASHSEED=random
matrix:
  include:
    - python: 3.7
      dist: xenial
    # defusedxml appears to be broken on Python 3.8:
    #- python: 3.8-dev
    #  dist: xenial
install:
  - pip install pip --upgrade
  - pip install coverage codecov flake8 pycalendar
  - sudo apt-get install -qq libneon27-dev curl python2.7
  - sudo apt-get install -qq cargo
  - python setup.py develop
script:
  - make style
  - make coverage
  - mv .coverage .coverage.unit
  # Retrieve litmus from Xandikos server for now, since webdav.org is down.
  - make coverage-litmus LITMUS_URL=https://www.xandikos.org/litmus-0.13.tar.gz
  - mv .coverage .coverage.litmus
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ]; then
        make coverage-vdirsyncer;
        mv .coverage .coverage.vdirsyncer;
    fi
  - make coverage-caldavtester
  - mv .coverage .coverage.caldavtester
after_success:
  - python -m coverage combine
  - codecov
cache:
  pip: true
