language: python
cache: pip
sudo: true
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy3
env:
  global: PYTHONHASHSEED=random
install:
  - pip install pip --upgrade
  - sudo apt-get install -qq libneon27-dev
  - python setup.py develop
script:
  - make check
  - make check-litmus
