language: python
cache: pip
sudo: true
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy3.3-5.2-alpha1
env:
  global: PYTHONHASHSEED=random
install:
  - pip install pip --upgrade
  - pip install coverage codecov flake8
  - sudo apt-get install -qq libneon27-dev
  - python setup.py develop
script:
  - make coverage
  - make style
  - make check-litmus
after_success:
  - codecov
