language: python
sudo: false
python:
  - "3.5"
  - "pypy3"
    # Python3.6 is disabled until https://github.com/tiran/defusedxml/issues/3 lands in travis.
    #  - "3.6"
env:
  global: PYTHONHASHSEED=random
cache:
  directories:
    - $HOME/.cache/pip
script:
  - pip install pip --upgrade
  - python -m unittest xandikos.tests.test_suite

